import React, { useCallback, useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, ArrowUpRight, ArrowRight, CloudRain, Sun, MessageSquare, Route as RouteIcon, Layers, Radio, Pause, Play, RotateCcw, SlidersHorizontal, MapPin, ChevronRight, Info, Clock, ShieldCheck, X, Zap, Loader2 } from 'lucide-react';
import './style.css';

type Area = {zone_id: string; name: string};
type Route = {route_id: string; name: string; zone_ids: string[]};
type Event = {event_id: string; source_type: string; observed_at: string; description: string; event_type: string; quality_flags: string[]; metrics: Record<string, number|string>};
type Feed = {status: string; observed_at: string|null; age_minutes: number|null};
type Sim = {running: boolean; scenario: string; speed: number; disabled: string[]; clock: string; tick: number; config: {window_minutes: number; weather_cadence: number}};
type State = {area: string; zone_id: string; summary: string; feeds: Record<string, Feed>; weather: {rain_mm_hour:number; temperature_c:number; condition:string}|null; complaints:{count:number; previous_count:number; baseline_ready:boolean; spike:boolean; trend:string}; transit:{slow_segments:number; observed_segments:number}; route:{available:boolean; baseline_minutes:number; current_minutes:number|null; additional_minutes:number|null; observed_at:string|null; missing_segments:string[]}|null; insight:{rule:string; explanation:string; detected_signals:string[]; supporting_event_ids:string[]; time_window:{start:string;end:string}}; events:Event[]; simulation:Sim};
type Overview = Area & {rule:string};
const time = (value: string|null) => value ? new Intl.DateTimeFormat('en-IN', {timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(value)) : 'No observation';
const scenarios: Record<string,string> = {normal:'Normal day',rain:'Heavy rain',rush:'Rush-hour congestion',obstruction:'Road obstruction'};
const observedHeadlines: Record<string,string> = {
  normal:'No disruption detected in the current observations.',
  heavy_rain:'Heavy rainfall is being observed in your neighbourhood.',
  rain_waterlogging_transit:'Rain, waterlogging reports, and slower transport may be linked.',
  transit_disruption:'Transport is taking longer than usual.',
  obstruction_transit:'Road obstruction reports and slower transport may be linked.',
};
async function api<T>(path:string, body?:unknown):Promise<T> {
  const response = await fetch('/api'+path, body ? {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)} : undefined);
  if(!response.ok) throw new Error(`Request failed (${response.status}). Please retry.`);
  return response.json();
}

function App(){
  const [started,setStarted] = useState(['#dashboard','#activity','#evidence'].includes(location.hash));
  const [areas,setAreas] = useState<Area[]>([]), [routes,setRoutes] = useState<Route[]>([]);
  const [zone,setZone] = useState('JAG'), [route,setRoute] = useState('');
  const [data,setData] = useState<State|null>(null), [overview,setOverview] = useState<Overview[]>([]);
  const [areaLoading,setAreaLoading] = useState(false);
  const selection = useRef(''); selection.current = zone + ':' + route;
  const [connected,setConnected] = useState(false), [error,setError] = useState(''), [busy,setBusy] = useState(false);
  const [controls,setControls] = useState(false), [evidence,setEvidence] = useState<unknown>(null);
  const refresh = useCallback(async()=>{
    try { const [state,grid] = await Promise.all([api<State>(`/state/${zone}${route?'?route='+route:''}`),api<Overview[]>('/overview')]); if(selection.current===zone+':'+route){setData(state); setOverview(grid); setError(''); setAreaLoading(false);} }
    catch(e){setError((e as Error).message); setAreaLoading(false);}
  },[zone,route]);
  const refreshRef = useRef(refresh); refreshRef.current = refresh;
  useEffect(()=>{Promise.all([api<Area[]>('/areas'),api<Route[]>('/routes')]).then(([a,r])=>{setAreas(a);setRoutes(r);setRoute(r.find(item=>item.zone_ids.includes('JAG'))?.route_id || '');}).catch(e=>setError(e.message));},[]);
  useEffect(()=>{
    const source=new EventSource('/api/live');
    source.onopen=()=>setConnected(true);
    source.onmessage=()=>{void refreshRef.current();};
    source.onerror=()=>setConnected(false);
    return ()=>{source.close();};
  },[]);
  useEffect(()=>{void refresh();},[refresh]);
  async function control(body:unknown){setBusy(true);try{await api('/simulation',body);await refreshRef.current();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  function selectZone(id:string){
    if(id===zone)return;
    const matchingRoute = routes.find(item=>item.route_id===route&&item.zone_ids.includes(id)) || routes.find(item=>item.zone_ids.includes(id));
    setZone(id);
    setRoute(matchingRoute?.route_id || '');
    setAreaLoading(true);
  }
  async function inspect(id:string){try{setEvidence(await api('/evidence/'+id));}catch(e){setError((e as Error).message);}}
  const sim=data?.simulation;
  const abnormal=data && data.insight.rule!=='normal';
  const title = !data ? 'Connecting to your neighbourhood' : Object.values(data.feeds).some(feed=>feed.status!=='fresh') ? 'A partial picture: some current data is unavailable.' : observedHeadlines[data.insight.rule] || 'Your neighbourhood, in context.';
  const additionalMinutes = data?.route?.available ? data.route.additional_minutes : null;
  const transitStatus = additionalMinutes === null ? 'Unavailable' : additionalMinutes < 5 ? 'Good' : additionalMinutes <= 20 ? 'Moderate' : 'Worst';
  const transitExplanation = additionalMinutes === null ? 'Complete route estimate unavailable' : additionalMinutes === 0 ? 'No additional travel time observed' : `Allow approximately ${additionalMinutes} extra ${additionalMinutes === 1 ? 'minute' : 'minutes'}`;
  const delaySummary = data?.summary || '';
  return <div className="app-shell">
    <header className="header"><button className="brand" onClick={()=>{setStarted(false);location.hash='';}}><span className="brand-icon"><Activity size={23}/></span>CityPulse<span className="brand-dot">.</span></button><span className="header-divider"/><span className="header-sub">THE LIVE CIVIC HEALTH DASHBOARD</span><span className="simulation-label"><span/>Simulation — synthetic data</span></header>
    {!started ? <main className="landing">
      <div className="landing-copy"><h1>A city has a pulse.<br/><span>Understand yours.</span></h1><p>Understand your neighbourhood through connected weather, civic complaints, and transport signals.</p><button className="primary big" onClick={()=>{setStarted(true);location.hash='dashboard';}}>Start Exploring <ArrowUpRight size={22}/></button><div className="landing-note"><ShieldCheck size={17}/> Entirely synthetic. Thoughtfully connected.<br/>No live Jaipur conditions or personal data.</div></div>
      <div className="city-art" aria-label="An abstract offline neighbourhood schematic"><div className="art-label">JAIPUR / A SIMULATED CITY</div><div className="art-grid">{Array.from({length:36},(_,i)=><div key={i} className={'block block-'+i}/>)}</div><div className="art-orbit orbit-one"/><div className="art-orbit orbit-two"/><div className="art-pin"><Activity size={30}/></div><div className="art-caption"><span className="live-dot"/> FIVE NEIGHBOURHOODS. THREE CONNECTED FEEDS.</div></div>
      <div className="landing-feeds">{[[CloudRain,'01','Weather','See the conditions.'],[MessageSquare,'02','Civic reports','Listen to the neighbourhood.'],[RouteIcon,'03','Transport','Understand the journey.']].map(([Icon,n,label,desc])=>{const I=Icon as typeof CloudRain;return <div key={String(n)}><I size={24}/><span className="mono">{String(n)}</span><h3>{String(label)}</h3><p>{String(desc)}</p></div>;})}</div>
    </main> : <div className="workspace"><aside className="sidebar"><div className="sidebar-top"><span className="tiny-label">WORKSPACE</span><a className="nav-item active" href="#dashboard"><Layers size={18}/> Overview <span>01</span></a><a className="nav-item" href="#activity"><Radio size={18}/> Live activity</a><a className="nav-item" href="#evidence"><ShieldCheck size={18}/> Connected evidence</a></div><div className="sidebar-bottom"><div className="mini-city"><MapPin size={20}/><div>Jaipur, Rajasthan<small>5 simulated neighbourhoods</small></div></div><div className="sidebar-disclaimer"><Info size={16}/><p>This is a civic simulation.<br/>Conditions are not actual<br/>Jaipur observations.</p></div></div></aside>
      <main className="dashboard" id="dashboard"><div className="page-heading"><div><div className="eyebrow">YOUR NEIGHBOURHOOD, CONNECTED</div><h1>City overview<span>.</span></h1><p>A clearer picture of what’s happening around you.</p></div><div className="connection"><span className={connected?'live-dot':'offline-dot'}/>{connected?'Live connection':'Reconnecting…'}<small>{sim?.running?'Simulation running':'Simulation paused'}</small></div></div>
        {error&&<div className="error" role="alert">{error} <button onClick={()=>void refresh()}>Retry</button></div>}
        <section className="toolbar"><div className={`regi-loader-bar ${areaLoading?'active':''}`}/><label><MapPin size={17}/><span>Neighbourhood</span><select value={zone} onChange={e=>selectZone(e.target.value)} aria-label="Neighbourhood">{areas.map(a=><option value={a.zone_id} key={a.zone_id}>{a.name}</option>)}</select>{areaLoading&&<Loader2 size={13} className="spin toolbar-spinner"/>}</label><div className="toolbar-line"/><label><RouteIcon size={17}/><span>Simulated route</span><select value={route} onChange={e=>{setRoute(e.target.value);setAreaLoading(true);}} aria-label="Simulated route"><option value="">Area overview</option>{routes.filter(r=>r.zone_ids.includes(zone)).map(r=><option value={r.route_id} key={r.route_id}>{r.name} · fictional</option>)}</select>{areaLoading&&route&&<Loader2 size={13} className="spin toolbar-spinner"/>}</label><button className={'secondary control-toggle '+(controls?'selected':'')} onClick={()=>setControls(!controls)}><SlidersHorizontal size={17}/> Simulation controls</button></section>
        {controls&&<section className="controls"><div className="controls-title"><div><strong>Your simulation lab</strong><p>One shared session for every connected tab.</p></div><span className="mono"><Clock size={15}/> {time(sim?.clock||null)} IST · minute {sim?.tick}</span></div><div className="control-fields"><label>Scenario<select aria-label="Scenario" value={sim?.scenario||'normal'} disabled={busy} onChange={e=>void control({scenario:e.target.value, target_zone:zone})}>{Object.entries(scenarios).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Speed<select aria-label="Speed" value={sim?.speed||2} onChange={e=>void control({speed:Number(e.target.value)})}>{[.25,1,2,5,10].map(n=><option key={n} value={n}>{n} sim min / sec</option>)}</select></label><button className="secondary" disabled={busy} onClick={()=>void control({running:!sim?.running})}>{sim?.running?<Pause size={16}/>:<Play size={16}/>} {sim?.running?'Pause':'Start'}</button><button className="secondary" disabled={busy} onClick={()=>void control({action:'reset', target_zone:zone})}><RotateCcw size={16}/> Reset</button><button className="primary" disabled={busy} onClick={()=>{const matchingRoute=routes.find(r=>r.zone_ids.includes(zone));if(!route&&matchingRoute){setRoute(matchingRoute.route_id);}void control({action:'fixture', target_zone:zone});}}><Zap size={16}/> Load 15-minute demo</button></div><div className="feed-toggles"><span>Enabled feeds</span>{['weather','complaint','transit'].map(f=><label key={f}><input type="checkbox" checked={!sim?.disabled.includes(f)} disabled={busy} onChange={e=>void control({disabled:e.target.checked ? sim?.disabled.filter(s=>s!==f) : [...(sim?.disabled||[]),f]})}/>{f==='complaint'?'Civic reports':f}</label>)}<small>Disabling a feed stops ingestion; existing evidence ages on the simulation clock.</small></div></section>}
        {!data?<section className="loading">Connecting to the simulation service…</section>:<>
        <div className={`settling-content ${areaLoading?'is-settling':''}`}>
        <section className={'summary '+(abnormal?'disrupted':'')}><div className="summary-main"><div className="summary-label"><span className={abnormal?'amber-dot':'live-dot'}/>{abnormal?'CONDITIONS TO WATCH':'NEIGHBOURHOOD SNAPSHOT'}<span className="summary-area">{areas.find(a=>a.zone_id===zone)?.name || data.area}</span></div><h2>{title}</h2><p>{delaySummary}</p><a href="#evidence" className="text-link">See the connected evidence <ArrowRight size={16}/></a></div><div className="summary-aside"><span>{route?'ADDITIONAL ROUTE TIME':'OBSERVED SLOW SEGMENTS'}</span><strong>{route?(data.route?.available?`+${data.route.additional_minutes}`:'—'):data.transit.slow_segments}<small>{route?'min':'segments'}</small></strong><p>{route?`${transitStatus} · ${transitExplanation}`:'Across this neighbourhood'}</p><span className="summary-stamp"><Clock size={13}/> {time(sim?.clock||null)} IST · simulated</span></div></section>
        <div className="metrics-grid"><section className="metric"><div className="card-heading"><span><CloudRain size={18}/> Weather</span><FeedBadge feed={data.feeds.weather}/></div><div className="metric-value">{data.weather?(data.weather.rain_mm_hour / 60).toFixed(3):'—'}<small>mm/min</small>{data.weather?.rain_mm_hour===0?<Sun className="metric-decoration" size={38}/>:<CloudRain className="metric-decoration" size={38}/>}</div><h3>{data.weather?.condition||'Observation unavailable'}</h3><p>{data.weather?`${data.weather.temperature_c}°C · rain per minute`:'Waiting for fresh weather observations'}</p><p className="rain-update-status">{sim?.running ? `Updates every ${sim.config.weather_cadence} simulated min · Now ${time(sim.clock)} IST` : 'Simulation paused · resume to update'}</p>{!sim?.running&&<button className="secondary" disabled={busy} onClick={()=>void control({running:true})}><Play size={16}/> Resume updates</button>}<div className="metric-footer">Observed {time(data.feeds.weather.observed_at)} IST <span>WEATHER FEED</span></div></section>
        <section className="metric"><div className="card-heading"><span><MessageSquare size={18}/> Civic reports</span><FeedBadge feed={data.feeds.complaint}/></div><div className="metric-value">{data.complaints.count}<small>reports</small><div className="bars" aria-hidden="true">{[data.complaints.previous_count,data.complaints.count].map((n,i)=><i key={i} style={{height:(n/Math.max(1,data.complaints.count,data.complaints.previous_count)*100)+'%',width:'18px'}}/>)}</div></div><h3 className={data.complaints.spike?'amber':''}>{data.complaints.trend}</h3><p>{data.complaints.baseline_ready?`${data.complaints.previous_count} in preceding window · ${sim?.config.window_minutes} min windows`:'Two observation windows needed for comparison'}</p><div className="metric-footer">Anonymous, deduplicated reports <span>CIVIC FEED</span></div></section>
        <section className="metric"><div className="card-heading"><span><RouteIcon size={18}/> Transport</span><FeedBadge feed={data.feeds.transit}/></div><div className="metric-value">{route?(data.route?.current_minutes??'—'):data.transit.observed_segments}<small>{route?'min total':'segments'}</small></div><h3>{route?`${transitStatus} · ${data.route?.baseline_minutes??'?'} min baseline`:!data.transit.observed_segments?'No fresh segment observations':data.transit.slow_segments?'Slower than baseline':'Within observed baseline'}</h3><p>{route?`${transitExplanation}. Route observed ${time(data.route?.observed_at||null)} IST`:'Select a route for a complete delay estimate'}</p><div className="metric-footer">Fictional routes · observed travel times <span>TRANSIT FEED</span></div></section></div>
        <div className="lower-grid"><section className="panel area-panel"><div className="panel-header"><div><h2>Across the neighbourhood</h2><p>Five areas. One connected picture.</p></div><span className="subtle-tag">OFFLINE SCHEMATIC</span></div><div className="zone-schematic"><svg viewBox="0 0 600 230" preserveAspectRatio="none" aria-hidden="true"><path d="M100 60L300 170L300 60L500 170L500 60M100 60L500 60M100 170L500 170"/></svg>{overview.map((a,i)=><button key={a.zone_id} className={`zone-card zone-${i} ${zone===a.zone_id?'chosen':''} ${areaLoading&&zone===a.zone_id?'loading-card':''}`} onClick={()=>selectZone(a.zone_id)}><span className="zone-code">{a.zone_id}{areaLoading&&zone===a.zone_id?<Loader2 size={12} className="spin"/>:<ArrowUpRight size={14}/>}</span><strong>{a.name}</strong><span>{areaLoading&&zone===a.zone_id?<span className="regi-sync-text">Settling data…</span>:<><i className={a.rule==='normal'?'live-dot':'amber-dot'}/>{a.rule==='normal'?'No rule triggered':'Conditions to watch'}</>}</span></button>)}</div><div className="schematic-note"><Info size={14}/> Conceptual layout, not a geographic map. Select an area to explore.</div></section>
        <section className="panel activity-panel" id="activity"><div className="panel-header"><div><h2>Recent activity</h2><p>Observations from {data.area}</p></div><Radio size={19}/></div><div className="timeline">{data.events.slice(0,6).map(e=><button className="timeline-item" key={e.event_id} onClick={()=>void inspect(e.event_id)}><span className={'timeline-icon '+e.source_type}>{e.source_type==='weather'?<CloudRain size={16}/>:e.source_type==='complaint'?<MessageSquare size={16}/>:<RouteIcon size={16}/>}</span><span><strong>{e.source_type==='transit'?`${e.metrics.observed_minutes} min · ${e.metrics.segment_id}`:e.description}</strong><small>{e.source_type} {e.quality_flags.length?'· '+e.quality_flags.join(', '):'· Normalized observation'}</small></span><time>{time(e.observed_at)}</time></button>)}{!data.events.length&&<p className="empty">No observations in this window.</p>}</div><div className="timeline-bottom">All times Asia/Kolkata (IST) <span>Inspect a record <ChevronRight size={13}/></span></div></section></div>
        <section className="panel evidence-panel" id="evidence"><div className="panel-header"><div><h2><ShieldCheck size={20}/> Why am I seeing this?</h2><p>Every connection has a traceable explanation.</p></div><span className="subtle-tag">RULE-BASED · NO AI CLAIMS</span></div><div className="evidence-content"><div><div className="signal-list">{data.insight.detected_signals.length?data.insight.detected_signals.map(s=><span key={s}>{s}</span>):<span>No active disruption signals</span>}</div><p>{data.insight.explanation}</p><div className="evidence-meta">Window {time(data.insight.time_window.start)}–{time(data.insight.time_window.end)} IST · Rule: <code>{data.insight.rule}</code></div></div><div className="support"><strong>{data.insight.supporting_event_ids.length} supporting observations</strong><div>{data.insight.supporting_event_ids.map((id,i)=><button key={id} onClick={()=>void inspect(id)}>Record {i+1} <ArrowUpRight size={13}/></button>)}</div><small>Possible links, not proven causes.</small></div></div></section>
        </div>
        </>}
        <footer><span><Activity size={14}/> CityPulse</span><span>Simulation — synthetic data <i/> Built for understanding, not real-world navigation.</span></footer>
      </main></div>}
    {evidence!==null&&<div className="modal-backdrop" onClick={()=>setEvidence(null)}><section className="modal" role="dialog" aria-modal="true" aria-label="Observation evidence" onKeyDown={e=>{if(e.key==='Escape')setEvidence(null);}} onClick={e=>e.stopPropagation()}><div className="panel-header"><h2>Observation evidence</h2><button autoFocus aria-label="Close evidence" onClick={()=>setEvidence(null)}><X/></button></div><p>Simulation — synthetic data. Original report and normalized record.</p><pre>{JSON.stringify(evidence,null,2)}</pre></section></div>}
  </div>;
}
function FeedBadge({feed}:{feed:Feed}){return <span className={'feed-badge '+feed.status}><i/>{feed.status==='fresh'?'Fresh':feed.status}</span>;}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
